Update CodeBuild Compute Type
aws-samples/aws-nuke-account-cleanser-example pull request #9
Opened 2023-12-14 02:02 UTC by mrutenberg

The CodeBuild Compute Type is set to BUILD_GENERAL1_2XLARGE causing an unexpectedly large cost to run this tool. Compute type has been dropped down to BUILD_GENERAL1_SMALL.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-27 00:21 UTC, aneescheckit approved these changes

2024-05-01 22:32 UTC, ryanpeach commented
https://github.com/aws-samples/aws-nuke-account-cleanser-example/issues/10

This needs to be merged

2024-05-02 00:53 UTC, aneescheckit approved these changes

2024-05-02 00:56 UTC, RWeissmandl approved these changes

2024-05-30 22:25 UTC, awsree requested changes
Hey thanks, since it's been some time, can you send this in fresh new PR, i just added --max-wait-retries option too to the nuke CLI in codebuild script to reduce waittimes

2024-06-01 14:41 UTC, awsree commented
ok updated changes to main with BUILD_GENERAL1_SMALL. Please feel free to test/open other requests if arm container works. Thanks

2024-06-01 14:41 UTC, closed without merging